import type { AgentMessage, ReflectionTrigger } from "./types.ts";
import { textFromContent } from "./content.ts";
import { nextGeneratedTimestamp } from "./message.ts";

const truncateForPrompt = (text: string, maxChars: number): string => {
	if (text.length <= maxChars) return text;
	return `${text.slice(0, maxChars - 15).trimEnd()} …[truncated]`;
};

const userTextsFromMessages = (messages: AgentMessage[]): string[] =>
	messages
		.filter((message) => message.role === "user")
		.map((message) => textFromContent(message.content))
		.map((text) => text.trim())
		.filter(Boolean);

const compactUserInstructionSnapshot = (messages: AgentMessage[]): string => {
	const userTexts = userTextsFromMessages(messages);
	if (userTexts.length === 0) return "Latest user instruction: (none found; user intent/authorization unclear)";
	return [
		"Recent user instructions, oldest first:",
		...userTexts.slice(-3).map((text, index) => `${index + 1}. ${truncateForPrompt(text, 260)}`),
		`Latest user instruction: ${truncateForPrompt(userTexts[userTexts.length - 1], 500)}`,
	].join("\n");
};

const userInstructionSnapshot = (messages: AgentMessage[]): string => {
	const userTexts = userTextsFromMessages(messages);

	if (userTexts.length === 0) {
		return [
			"USER-INSTRUCTION / GOAL FRAME SNAPSHOT",
			"No explicit non-empty user messages found in the current history. Treat current user intent and authorization as unclear.",
		].join("\n");
	}

	const latest = userTexts[userTexts.length - 1];
	const formatList = (items: string[]) => items.map((text, index) => `${index + 1}. ${truncateForPrompt(text, 450)}`).join("\n");

	return [
		"USER-INSTRUCTION / GOAL FRAME SNAPSHOT",
		"Latest explicit user instruction is the binding local scope. Do not create new work beyond it.",
		"Recent user messages, oldest first, up to 5:",
		formatList(userTexts.slice(-5)),
		"Latest explicit user instruction:",
		truncateForPrompt(latest, 700),
	].join("\n");
};

const triggerDescription = (trigger: ReflectionTrigger): string => {
	if (trigger === "agent_end") return "the agent is about to return control to the user";
	if (trigger === "manual") return "the user manually requested self-reflection with /self-reflect-now";
	return "configured cadence before the next normal LLM call";
};

export const reflectorAttributionContract = [
	"Attribution boundary: your output is generated by the pi-self-reflect extension, not by the user.",
	"Your output may be shown to the user and may be injected into the driving agent as extension-generated process support.",
	"Do not say or imply that the user wants, asked, requested, or is telling the driver anything.",
	"If diagnosing process, refer to the active agent as 'the driver', not as 'the user'.",
	"Do not add task requirements; only provide process-control support for the existing user request.",
];

const goalBoundaryRules = [
	"Goal-contract hierarchy: the user's latest explicit instruction is the highest-priority local goal and scope boundary.",
	"Use the USER-INSTRUCTION / GOAL FRAME SNAPSHOT to distinguish explicit long-term session goal from current short-term instruction.",
	"The current short-term instruction overrides the long-term/session goal.",
	"The broader session/project goal matters only inside the latest user-authorized scope; never create the next task yourself.",
	"Reflection must protect the user's current instruction boundary, not expand it.",
	"Before any NOTE, STEER, or PAUSE_USER, ask: what exactly did the user most recently authorize, has the driver satisfied it, and would this output cause new work beyond it?",
	"If the driver completed a bounded request such as read, summarize, inspect, explain, or report, do not recommend new investigation, execution, edits, server actions, or verification unless needed to correct that same response.",
	"Agent-end rule: when the driver is about to return control, do not propose the next step. Only flag issues that affect correctness/safety/scope of the response just produced.",
	"A possible follow-up is for the user to choose; it is not a driver instruction.",
];

const groundingRules = [
	"Epistemic boundary: you do not know more task facts than the driver; you only have the existing conversation/tool history and a different process-audit angle.",
	"Ground every NOTE, STEER, or PAUSE_USER in known facts already present in the history: user input, tool output, fetched documentation, file contents, or explicit driver observations.",
	"If a point is only a hypothesis, frame it as an evidence gap or process risk, not as a conclusion or implementation instruction.",
	"When steering, cite the known fact or evidence gap briefly; do not behave as a hidden second implementer or agenda generator.",
];

const noSolutionArchitectingRules = [
	"You are a process auditor, not a technical architect, implementer, debugger, reviewer, or assistant answering the user.",
	"You cannot talk to the user, run tools, inspect more files, edit code, execute commands, approve actions, or continue the task.",
	"Do not propose concrete technical fixes, terminal commands, code edits, config edits, dependency/library choices, Dockerfile/image changes, migrations, or workaround recipes.",
	"Do not introduce new technical claims, commands, config values, library choices, workaround recipes, or architecture alternatives unless the driver already established them from observed evidence in this session.",
	"Focus only on process quality: loops, missing evidence for a claim already being made, unsafe/destructive action, unapproved scope expansion, user-contract drift, conflicting requirements, or failure to distinguish fact from hypothesis.",
	"Never use first-person execution language such as I, I'll, I will, let me, let's, we should, agreed, recommended patch, or next I will.",
];

export const outcomeSelectionRules = [
	"Default to bare OK. The normal expected answer is exactly OK:",
	"Choose the weakest outcome that safely helps the driver.",
	"Do not repeat, summarize, endorse, approve, or rephrase the driver's current plan or analysis.",
	"Return exactly OK: if your output would merely restate what the driver already said, already noticed, or was already about to do.",
	"Use NOTE, STEER, or PAUSE_USER only when you add a materially new process risk, contradiction, missing verification, or user-contract issue within the latest user-authorized scope.",
	"Before any non-OK output, ask: would this materially change the driver's next process step without adding a new task or technical solution? If not, return exactly OK:",
	"Verification is task-sensitive: for read-only inspect/explain/find/report tasks, evidence usually means citations, quoted observations, and separating confirmed facts from hypotheses; do not ask for tests/smoke checks unless code changed or runtime behavior is being claimed.",
	"For implementation/code-change tasks, proportional evidence may include tests, typechecks, smoke checks, or functional validation.",
	"Do not convert grounding/citation gaps into generic test-running advice.",
	...goalBoundaryRules,
	...groundingRules,
	...noSolutionArchitectingRules,
	"OK: must be exactly OK: unless there is a material non-redundant process risk. Do not append advice, checks, verification reminders, summaries, or praise to OK:.",
	"NOTE: descriptive visible audit observation only, for the log/user view; not a driver instruction. State an observed process risk or evidence gap without action verbs. Invalid NOTE style: Verify X, Check Y, Consider Z, Try W. Valid NOTE style: NOTE: No test evidence is visible for the changed parser path.",
	"STEER: process correction only, max 2 short bullets. It may say to stop looping, stay within scope, distinguish fact from hypothesis, verify evidence for a claim already being made, or ask before risky/scope-expanding action. It must not include a technical fix or workaround recipe.",
	"PAUSE_USER: last resort only. Use only when known facts show the driver lacks necessary user intent/preference, credentials/secrets, approval for a risky or destructive action, or must resolve conflicting requirements before safe continuation.",
	"Do not use PAUSE_USER merely because the next obvious implementation/debugging step requires ordinary execution.",
	"Do not ask the user to choose between proceeding and 'a different approach' unless there is a real product/intent decision the driver cannot infer or verify from known facts.",
	"If a useful observation would become a new task beyond the user's latest instruction, return exactly OK: or use a descriptive NOTE that is safe as visible audit only, not STEER.",
];

export const outputContractRules = [
	"OUTPUT CONTRACT: Return exactly ONE line. First token must be OK:, NOTE:, STEER:, or PAUSE_USER:.",
	"Default valid output: OK:",
	"Valid NOTE example: NOTE: No test evidence is visible for the changed parser path.",
	"Valid NOTE for inspection: NOTE: The draft mixes confirmed observations with inferred motives; evidence labels are missing.",
	"Valid STEER example: STEER: Known fact: the driver is about to exceed the latest read-only request. Return control to the user instead of starting new work.",
	"Valid STEER for inspection: STEER: The driver is about to present inferred motives as facts; label them as confirmed, likely, or speculative with evidence.",
	"Invalid STEER for inspection: STEER: Run automated verification or smoke tests before inspecting further.",
	"Valid PAUSE_USER example: PAUSE_USER: The next action is destructive and lacks explicit user approval; ask the user for approval before continuing.",
	"Invalid: OK: verify the smoke test before continuing.",
	"Invalid: NOTE: Verify the Dockerfile change before restarting.",
	"Invalid: STEER: Install Python 3.11 and update the Dockerfile COPY path.",
	"Invalid: Agreed: I’ll update the prompt and smoke-test it.",
	"Do not answer as the assistant/driver. Do not say Agreed, I will, I'll, Let me, We should, or similar execution language.",
];

export type ReflectionViewPrompt = {
	id: string;
	name: string;
	message: AgentMessage;
};

const compactViewContract = [
	"You are not the assistant. You are a classifier that outputs exactly one label line.",
	"Allowed outputs only:",
	"CLEAR:",
	"ISSUE: <one short process risk or evidence gap>",
	"If no issue, output exactly CLEAR:",
	"Do not explain. Do not mention prompts. Do not answer the user. Do not use markdown.",
	"Invalid output examples: Yes — this confirms the latest version is loaded. / Let me check. / Good catch.",
	"Final answer must be only the label line.",
];

const buildViewPrompt = (
	checkpoint: number,
	trigger: ReflectionTrigger,
	messages: AgentMessage[],
	id: string,
	name: string,
	focus: string[],
): ReflectionViewPrompt => ({
	id,
	name,
	message: {
		role: "user",
		content: [
			{
				type: "text",
				text: [
					`REFLECTION VIEW — ${name}.`,
					...compactViewContract,
					`Checkpoint #${checkpoint}; trigger: ${triggerDescription(trigger)}.`,
					compactUserInstructionSnapshot(messages),
					"Classify only this focus:",
					...focus,
					"Only flag issues grounded in known conversation/tool history and within latest user scope.",
					"Answer now with exactly CLEAR: or ISSUE: ...",
				].join("\n"),
			},
		],
		timestamp: nextGeneratedTimestamp(messages),
	},
});

export const buildReflectionViewPrompts = (checkpoint: number, trigger: ReflectionTrigger, messages: AgentMessage[]): ReflectionViewPrompt[] => [
	buildViewPrompt(checkpoint, trigger, messages, "process", "Loop / process guard", [
		"Detect loops, repeated plans, stalled progress, churn without evidence, or failure to adapt after tool/test feedback.",
		"Ignore ordinary unfinished work unless the driver is repeating or about to finalize prematurely.",
	]),
	buildViewPrompt(checkpoint, trigger, messages, "contract", "User-contract / scope guard", [
		"Check alignment with the latest explicit user instruction, explicit constraints, authorization boundaries, and scope.",
		"Flag only real scope drift, missing required user approval, conflicting requirements, or attribution/user-intent mistakes.",
	]),
	buildViewPrompt(checkpoint, trigger, messages, "verification", "Verification / completion auditor", [
		"Check whether the driver is about to claim completion without proportional evidence for claims already being made.",
		"Flag missing verification only when it affects the current authorized task and is not already acknowledged by the driver.",
	]),
	buildViewPrompt(checkpoint, trigger, messages, "grounding", "Grounding / assumption checker", [
		"Check whether the driver's claims or likely non-OK reflection findings are grounded in known facts from the history.",
		"Flag speculation, hidden technical assumptions, or unsupported conclusions as evidence gaps, not as implementation advice.",
	]),
];

export const buildReflectionCombinerPrompt = (
	checkpoint: number,
	iteration: number,
	trigger: ReflectionTrigger,
	messages: AgentMessage[],
	viewOutputs: Array<{ id: string; name: string; output: string }>,
): AgentMessage => ({
	role: "user",
	content: [
		{
			type: "text",
			text: [
				"REFLECTION COMBINER CLASSIFIER.",
				"Output exactly one line. First token must be OK:, NOTE:, STEER:, or PAUSE_USER:.",
				"Default: OK:",
				"You are not the assistant. Do not answer the user. Do not inspect code. Do not discuss the reflection system. Do not explain failures.",
				"Combine only the sanitized expert findings below. Ignore malformed/excluded expert outputs; they are not findings.",
				"Use STEER only for a material driver-process correction. Use PAUSE_USER only for missing user intent/approval/conflict.",
				"Task-sensitive verification: inspection/explanation/reporting needs citations and fact-vs-hypothesis labels; implementation changes may need tests/typechecks/smoke checks.",
				"Do not turn inspection grounding gaps into generic test-running advice.",
				`Checkpoint #${checkpoint}; iteration: ${iteration}; trigger: ${triggerDescription(trigger)}.`,
				compactUserInstructionSnapshot(messages),
				"Sanitized expert findings:",
				...viewOutputs.map((view) => `${view.id}: ${truncateForPrompt(view.output, 260) || "CLEAR:"}`),
				"Allowed final forms:",
				"OK:",
				"NOTE: <one concise visible-only process audit observation>",
				"STEER: <one concise driver-process correction>",
				"PAUSE_USER: <one concise needed user decision>",
				"Invalid: Both the combiner and its retry failed. Invalid: Let me look. Invalid: Here is a summary.",
				"FINAL ANSWER ONLY:",
			].join("\n"),
		},
	],
	timestamp: nextGeneratedTimestamp(messages),
});

export const buildSingleReflectionPrompt = (checkpoint: number, iteration: number, trigger: ReflectionTrigger, messages: AgentMessage[]): AgentMessage => ({
	role: "user",
	content: [
		{
			type: "text",
			text: [
				"SINGLE SELF-REFLECTION AUDIT — output exactly one line starting OK:, NOTE:, STEER:, or PAUSE_USER:.",
				"You are not the assistant/driver. Do not answer the user. Do not choose implementation actions. Do not create new work.",
				"Default: OK:",
				`Checkpoint #${checkpoint}; iteration: ${iteration}; trigger: ${triggerDescription(trigger)}.`,
				compactUserInstructionSnapshot(messages),
				"Silently check these lenses, then combine them yourself:",
				"1. Loop/process: repeated plans, stalled progress, churn without evidence, failure to adapt after feedback.",
				"2. User-contract/scope: latest explicit user instruction, constraints, authorization, attribution boundaries.",
				"3. Verification/completion: completion claims need proportional evidence for the current authorized task; inspection tasks need citations/fact labels, while implementation tasks may need tests/typechecks.",
				"4. Grounding/assumptions: non-OK findings must be grounded in known history/tool facts, not speculation.",
				"Do not turn read-only inspection grounding gaps into generic test-running advice.",
				"Outcome rules:",
				"OK: no material process issue.",
				"NOTE: one concise visible-only audit observation; no action directive.",
				"STEER: one material process correction within latest user scope.",
				"PAUSE_USER: only for missing user intent/preference, risky approval, credentials/secrets, or conflicting requirements.",
				"Invalid: Good catch. Invalid: I will fix it. Invalid: Here is a summary.",
				"Return one line only.",
			].join("\n"),
		},
	],
	timestamp: nextGeneratedTimestamp(messages),
});

export const buildReflectionPrompt = buildSingleReflectionPrompt;
